### ISSUE TITLE
Test helpers

### ISSUE THREAD

**Issue by nightscape** [opentracing/opentracing-ruby#12]
We will be contributing and extending some Ruby OT tracers.
For this it would be helpful to have something like a `RecordingTracer` that behaves like a sensible Tracer and whose recorded trace/span history can later be checked in the tests.
I saw that you are using `Minitest::Mock` instances in the tests here, but for more complicated scenarios a `RecordingTracer` imo makes more sense because you don't have to specify each and every possible interaction up-front.

So my questions would be:

- Is this the right place to add a `RecordingTracer`?
- Would it be ok to also add RSpec matchers here that allow one to write something like
  ```ruby
  expect(tracer).to have_traced(trace_id: 123)
  ```
  Of course those would not be auto-required so that they don't break libraries that do not use RSpec.

**Comment by bhs** [comment]
I think you are advocating for a non-production "mock" Tracer. That could be added to github.com/opentracing-contrib easily; that said, I'm also fine with merging it into the core repo since it's generally a really useful thing for, well, writing tests!

I would not want a production-style Tracer or Tracer helper in the core lib, though.

See https://github.com/opentracing/opentracing-java/tree/master/opentracing-mock and https://github.com/opentracing/opentracing-go/tree/master/mocktracer

cc @tedsuo

**Comment by tedsuo** [comment]
Thanks @nightscape. This is just a mock/testing tool, correct? As long as it is in `test` and is submitted as part of an improved test suite (AKA it's actually used and is shown to improve testing) then I'm all for it.

BTW, we want the ruby API to be extended to include the same ActiveSpan concepts we are adding to Java and Python. If you're interested in Tracer development in Ruby and would like to be a part of that effort, let me know.

**Comment by nightscape** [comment]
About the improvement of test code:
I think more or less every middleware (Rack, Faraday, RestClient, ...) will need something like this to check if the tracer was called correctly.
E.g. [`ruby-rack-tracer` uses a logging tracer](https://github.com/opentracing-contrib/ruby-rack-tracer/blob/master/spec/rack/tracer_spec.rb) and then checks the content of the log messages

About where to put the files: Putting them into `test` is usually not an option because the `test` folder doesn't get packaged into the gem. I see three options here:

1. Put it into the `opentracing-ruby` gem but make it clear that this is not a production tracer (via file and module names, e.g. `OpenTracing::Mock::Tracer` or `OpenTracing::Recording::Tracer`).
2. Put it into a separate gem in the same repo.
3. Put it into a separate gem in a different repo.

Option 1. makes co-evolution and discoverability easiest and maybe some middlewares might reuse the `Span` or `SpanContext` implementation if they don't bother implementing them themselves.
Option 2. would still allow for co-evolving the mock implementation relatively easily but require some more work for setting up things like Travis, Code Climate, etc.
Option 3. would make Travis, Code Climate, etc. trivial again, but reduce discoverability and natural co-evolution.

Did I miss some options, advantages / disadvantages?

If time allows and I'm more proficient with OpenTracing, I'll happily help with the `ActiveSpan` stuff :smiley:

**Comment by indrekj** [comment]
I like the third option: `ruby-rspec-tracer`, `ruby-mock-tracer` or whatever.  I think this repository as an interface for all the tracers. If I'm adding tracing support for a library (e.g. ruby-rack-tracer) then I would gladly use a mock/rspec tracer to ensure the code works correctly. I however don't see a point of including it in the production code.

This would also keep this repository changes (issues/PRs) related to the interface and not rspec or any other framework.

**Comment by iaintshine** [comment]
I think I got you covered. Had exactly the same need during works on some instrumentation libraries (e.g. [rails-tracer](https://github.com/iaintshine/ruby-rails-tracer)). It was obvious very quickly that there is a need for a "mock tracer" (well I called it "test tracer"). But even that wasn't enough as the testing code included lots of boilerplate which blinded tests. RSpec matchers seemed like a solution. That's why I've implemented a [test-tracer](https://github.com/iaintshine/ruby-test-tracer) and [tracing-matchers](https://github.com/iaintshine/ruby-tracing-matchers) (which works together with test-tracer).    

As you mentioned rack and faraday tracers, this is how the tests look like if used together with the gems:
* [faraday-tracer](https://github.com/opentracing-contrib/ruby-faraday-tracer/compare/master...iaintshine:use-tracing-matchers?expand=1)
* [rack-tracer](https://github.com/opentracing-contrib/ruby-rack-tracer/compare/master...iaintshine:use-tracing-matchers?expand=1)

Hope you find them useful.

**Comment by nightscape** [comment]
@iaintshine Very nice work! This is exactly what I had in mind! :100: :+1: 
I'm closing this issue then.
